name: Continuous Integration
on:
  push:
    branches: [ main, features/** ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Build, Format, Clippy, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --all-targets -- -D warnings
      - name: Format Check
        run: cargo fmt -- --check
      - name: Test
        run: cargo test --verbose
