name: Continuous Integration

on:
  push:
    branches: [ main, features/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build, Format, Clippy, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1.8.0
        with:
          rust-version: stable

      - name: Build
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy --all-targets -- -D warnings

      - name: Format Check
        run: cargo fmt -- --check

      - name: Test
        run: cargo test --verbose
